name: tests

on:
  push:
    branches:
      - dev
      
jobs:

  tests:
      name: run tests
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker-compose up tests
